version: '3'
services:
  web:
    build: .
    container_name: my-web
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./src:/var/www/html
    networks:
      - my-network
    depends_on:
      - db
  db:
     image: mysql:latest
    container_name: my-db
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: cc_computing
      MYSQL_USER: khoitv
      MYSQL_PASSWORD: khoitv@123
      MYSQL_ROOT_PASSWORD: 123@123Aa
       networks:
      - my-network
  phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
    container_name: my-dbadmin
    environment:
      PMA_HOST: db
      #PMA_USER: db_user
      #PMA_PASSWORD: dbPass@123
    ports:
      - "8080:80"
    restart: always
    networks:
      - my-network
    depends_on:
      - db

  
